### PR TITLE
Minor CSS fix for playground output terminal with scrollbar

### PR DESCRIPTION
**Pull request by skdarekar**
## What does this PR do?
Minor CSS fix for playground terminal scrollbar

## What packages have been affected by this PR?
None

## Types of changes
CSS change
What types of changes does your code introduce to this project?
Minor CSS Change
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes an issue)

- [ ] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Package version increase in cli package?
No

## Checklist before merging

_Put an `x` in the boxes that apply_

- [X] These changes have been thoroughly tested.

- [ ] Changes need to be immediately published on npm.

### CODE REVIEW

**Comment by tbhaxor** [comment]
Hey @skdarekar No need to create an issue for such small fixes in future.

**Review by tbhaxor — APPROVED** [review]
lgtm

**Comment by Bilalssbb** [comment]
> ### <span aria-hidden="true">✅</span> Deploy Preview for *bhailang-preview* ready!
> 
> 
> |  Name | Link |
> |---------------------------------|------------------------|
> |<span aria-hidden="true">🔨</span> Latest commit | 0cef62fee7dbf5f743c480ab0f73cd6be5662132 |
> |<span aria-hidden="true">🔍</span> Latest deploy log | https://app.netlify.com/sites/bhailang-preview/deploys/6240950d1cac0200098a5a2b |
> |<span aria-hidden="true">😎</span> Deploy Preview | https://deploy-preview-259--bhailang-preview.netlify.app |
> |<span aria-hidden="true">📱</span> Preview on mobile | <details><summary> Toggle QR Code... </summary><br /><br />QR Code<br /><br />_Use your smartphone camera to open QR code link._</details> |
> ---
> 
> _To edit notification comments on pull requests, go to your [Netlify site settings](https://app.netlify.com/sites/bhailang-preview/settings/deploys#deploy-notifications)._

**Comment by skdarekar** [comment]
Can we merge this @tbhaxor?

**Comment by tbhaxor** [comment]
> Can we merge this @tbhaxor?

Bhai mujhe write permission nhi hai repo par. @aniketsingh0104 Can we merge this if looks good to you?

**Comment by aniketsingh0104** [comment]
This is not really needed.

**Comment by aniketsingh0104** [comment]
If you see any bug then please provide evidence.

**Pull request closed without merging**
