### PR TITLE
✅ Create Issue Form for new contributors

### PR DESCRIPTION
**Pull request by Lakhankumawat**
Things Done in this PR :

1. Setup an issue form template for the REPO
2. Customize the form fields based on the type of contribution you want 
3. Simple and Convinienet 
4. Structured and More Organised
5. Supports Github Actions and Bots Labelling

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
Since there is no CODE_OF_CONDUCT and Contributing.md in the REPO if have by default made it point to README of the REPO

**Review by aniketsingh0104 — CHANGES_REQUESTED** [review]
Please make ISSUE_TEMPLATE folder inside .github folder directly and not inside workflows , see [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)

**Review by Lakhankumawat — COMMENTED** [review]
Done 💯 , Acutally i didn't saw it though thanks for pointing though . If you are okay i can set up workflows for this repo , basic workflows .

**Comment by Lakhankumawat** [comment]
Or You can do it on your own from here ⬇️

Example : https://github.com/Lakhankumawat/LearnCPP/tree/main/.github

For any helps : Always there

**Comment by aniketsingh0104** [comment]
> Or You can do it on your own from here ⬇️
> 
> Example : https://github.com/Lakhankumawat/LearnCPP/tree/main/.github
> 
> For any helps : Always there

You can go ahead and submit PRs for them. Thanks for your contribution.

**Review by aniketsingh0104 — APPROVED** [review]
LGTM.

**Pull request merged**
