### PR TITLE
chore : added issue templates and PR templates

### PR DESCRIPTION
**Pull request by Ayush7614**
Fix #128 
This PR contains
* Added Standard issue templates in YAML format
* Added PR template
* Replace PR template in right place

### CODE REVIEW

**Comment by Ayush7614** [comment]
cc @ankitchouhan1020

**Comment by Ayush7614** [comment]
cc @ristri @aniketsingh0104 @ankitchouhan1020

**Comment by ritikbanger** [comment]
You can change the language from English to Hinglish to be more "Desi".

**Comment by aniketsingh0104** [comment]
Alredy fixed.

**Pull request merged**
