### PR TITLE
feat: replace bhai with dost

### PR DESCRIPTION
**Pull request by chaitanyadeorukhkar**
Bhaio aur behno, hum sab dost hai.

co-authored with: @kamleshchandnani

### CODE REVIEW

**Comment by ankitchouhan1020** [comment]
Are... aapne to bhailang se bhai he remove kr diya 😆

**Review by impratik7 — COMMENTED** [review]
Hi @chaitanyadeorukhkar I understand, but we need bhai in bhailang I think. Other contributers can provide their opinions too.

**Comment by BRO3886** [comment]
image

@chaitanyadeorukhkar 

(meant to be taken as light-hearted banter, thx)

**Comment by aniketsingh0104** [comment]
Thanks for your contribution folks but we are going to stay with "bhai" keyword because its the core gist of the whole language and at this point we won't be able to make any change, maybe you folks can make - "DostLang" ❤️ .

One more thing - "Bhai" is a feeling, not just a keyword. haha.

Closing this one.

**Pull request closed without merging**
